### ISSUE TITLE
Implement according to Storage API

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/tableschema-elasticsearch-py#1]
# Overview

An established way for `tableschema` storage integrations is writing a driver based on Storage API - https://github.com/frictionlessdata/tableschema-py#storage

Examples:
- https://github.com/frictionlessdata/jsontableschema-sql-py
- https://github.com/frictionlessdata/jsontableschema-bigquery-py
- https://github.com/frictionlessdata/jsontableschema-pandas-py

The main responsibility of the Elasticsearch driver is encapsulate Table Schema to Elasticsearch type mappings and implement Storage API (common operations like read and write to work with storage). 

Contributing notes:
- [OKI coding standards](https://github.com/okfn/coding-standards)

# Plan

- [x] feel free to write to @roll, @akariv, https://gitter.im/frictionlessdata/chat and this issue thread for any questions, ideas and anything
- [x] preferably sync with @akariv about already existent code - #2
- [x] bootstrap this repository based on one of OKI examples (SQL/BigQuery/Pandas drivers or https://github.com/okfn/oki-py)
- [x] implement Storage API skeleton based on SQL/BigQuery/Pandas examples
- [x] implement type mappings based on SQL/BigQuery/Pandas examples
- [x] integrate mappings into Storage API
- [x] write high-level tests to ensure the driver works as expected

**Comment by roll** [comment]
@pwalsh 
will do

**Comment by pwalsh** [comment]
@roll looks like @akariv has done much of this. Can you do a review over the next week or so and highlight anything we need to fix for a first release

**Comment by roll** [comment]
@pwalsh 
will do

**Comment by pwalsh** [comment]
@brew is now working on this.

**Comment by brew** [comment]
@pwalsh:

As you say, @akariv has already done the bulk of the implementation as far as creating and writing tableschema data to elasticsearch is concerned. I've created some issues (#3, #5, #6) and a PR (#4), to detail what's left to implement, and started to flesh out the `storage.describe()` method in [this branch](https://github.com/frictionlessdata/tableschema-elasticsearch-py/tree/6/es-to-ts). Either someone else can pick this up, or I can continue when I return from holiday.

**Comment by pwalsh** [comment]
thanks @brew !
