### ISSUE TITLE
Maintainer / Lead

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/tableschema-elasticsearch-py#16]
As per https://github.com/frictionlessdata/project/issues/695#issuecomment-911262730

Would be super if @akariv and I could be marked as leads and have maintainer access here, ands also on the pypi package.

**Comment by roll** [comment]
Hi @pwalsh,

I had added all the tableschema/datapackage libs to your permissions group. Also, I changed it now from maintain to admin (might have been a problem to disable Travis check?).

Please go ahead and change the leads files or I can do it on Monday.

**Comment by akariv** [comment]
Looks good @roll, thank you.
- I removed travis-ci as a requirement 
- I added @pwalsh to the owners of https://pypi.org/project/tableschema-elasticsearch/
- I've opened #17 as a follow up to this.
