### ISSUE TITLE
Set up test/build GitHub Actions

### ISSUE THREAD

**Issue by akariv** [frictionlessdata/tableschema-elasticsearch-py#17]
Following the removal of travis-ci as the CI environment, replace it with GH actions.

**Comment by roll** [comment]
We have migrated some libraries to Github Actions - https://github.com/frictionlessdata/livemark/blob/main/.github/workflows/general.yml. It works great, probably just might be ported

**Comment by pwalsh** [comment]
done by @akariv in https://github.com/frictionlessdata/tableschema-elasticsearch-py/tree/main/.github/workflows
