### ISSUE TITLE
Dump some current working code in here

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/tableschema-elasticsearch-py#2]
@akariv has some working code for this. It is not according to the Storage API for Table Schema but that is fine. Let's just get the code dumped into here, so that one of us can take it as a starting point for building out the actual library.

**Comment by roll** [comment]
@akariv 
Adam could you please take a look when you'll be having some time for it

**Comment by roll** [comment]
DONE in 7f5b033e40393f750e0fb2b79bd0d3dd573953ba
