### ISSUE TITLE
Prefix `fmt:` is deprecated in tableschema

### ISSUE THREAD

**Issue by brew** [frictionlessdata/tableschema-elasticsearch-py#5]
The date mappers need to be adjusted so they aren't dependent on `fmt:` being prepended to date types in the descriptor.

See: https://github.com/frictionlessdata/tableschema-elasticsearch-py/blob/fa77da7a59356cf44df1aec6d8f88d1a6d7fd4f7/tableschema_elasticsearch/mappers.py#L19

**Comment by akariv** [comment]
I agree - but we need to decide whether to conform to pre v.1 schema or
wait for it to become officially released.
